source_dirs: 
  - "./logs/"
dest_dirs:
  images: 
    path: "/path/to/image"
    filters:
      - name: extensions
        config:
          extensions: [".jpg", ".png"]
    strategy: 
      name: "date"
      config:
        format: "2006/01"
  videos: 
    path: "/path/to/videos"
    filters:
      - name: extensions
        config:
          extensions: [".mp4", ".mov"]
    strategy: 
      name: dirchain
  school:
    path: "studies"
    filters:
      - name: script
        config:
          scriptPath: "./path/to/script"
    strategy: 
      name: dirchain
regroup:
  enable: true
  path: "/path/to/regroup"
  mode: "symlink"  # or "hardlink" or "copy"
  strategy: 
    name: localisation
