run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - gosimple
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
